name: TegraExplorer builder

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v1
        
    - name: Build TegraExplorer
      run: |
        sudo apt update -y
        sudo apt install build-essential -y
        alias py=python3
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: TegraExplorer
        path: | 
          output/TegraExplorer.bin
          output/TegraExplorer_small.bin
